### ISSUE TITLE
[Bug]: issue with connecting to any source provider

### ISSUE THREAD

**Issue by eliluong** [fastenhealth/fasten-onprem#364]
### Contact Details

eliluong@gmail.com

### What happened?

Whenever I add a new source (search for source, click on correct source, then click `Connect`), it gets stuck on the spinner. If I look at console, it has the error below. If I refresh the page, and repeat the steps above and connect to the same provider, it will proceed to the provider's connection screen.

### Flavor

Docker

### Version

main#6d6647a

### Relevant log output

```shell
ERROR Error: Uncaught (in promise): TypeError: u.Sha256 is not a constructor
TypeError: u.Sha256 is not a constructor
    at ai.getDigest (webcrypto-liner.shim.mjs:8444:18)
    at ai.<anonymous> (webcrypto-liner.shim.mjs:8456:27)
    at Generator.next (<anonymous>)
    at webcrypto-liner.shim.mjs:5374:69
    at new e (zone.min.js:29:3049)
    at $ (webcrypto-liner.shim.mjs:5353:12)
    at ai.digest (webcrypto-liner.shim.mjs:8455:14)
    at v1.<anonymous> (webcrypto-liner.shim.mjs:9503:26)
    at Generator.next (<anonymous>)
    at webcrypto-liner.shim.mjs:5374:69
    at O (zone.min.js:29:1993)
    at zone.min.js:29:1068
    at zone.min.js:29:1174
    at e.invoke (zone.min.js:14:7205)
    at Object.onInvoke (core.mjs:26274:33)
    at e.invoke (zone.min.js:14:7145)
    at t.run (zone.min.js:14:2289)
    at zone.min.js:29:2798
    at e.invokeTask (zone.min.js:14:7889)
    at Object.onInvokeTask (core.mjs:26261:33)
```

**Comment by AnalogJ** [comment]
Hey @eliluong 
Are you accessing your fasten instance via IP Address? 
Can you share your config file?

Could it be related to this issue - https://github.com/fastenhealth/fasten-onprem/issues/14 ?

**Comment by eliluong** [comment]
I am accessing via `hostname.lan`, and not https. But it sounds similar to my error. 

I run it via docker compose:
`
version: '3.8'

services:
  fasten-health:
    image: ghcr.io/fastenhealth/fasten-onprem:main
    ports:
      - "7070:8080"
    volumes:
      - ./db:/opt/fasten/db
      - ./cache:/opt/fasten/cache
`

**Comment by dwradcliffe** [comment]
This might be stale, is this still an issue?

**Comment by AnalogJ** [comment]
I think this is stale. I have a polyfill now for non-https crypto usage with a custom domain.
