### ISSUE TITLE
[Bug]: If the CADA to FHIR service is unavailable (503) the UI does not indicate that anything is wrong.

### ISSUE THREAD

**Issue by ronnoceel** [fastenhealth/fasten-onprem#448]
### What happened?

STR:
Navigate to /web/sources and upload a CADA xml file.
Accept the terms to submit to the converter.
https://api.platform.fastenhealth.com/v1/app/ccda-to-fhir is unavailable for some reason

EXPECTED:
The user is alerted that the service is unavailable.

ACTUAL:
instead the model closes and nothing happens. An error is printed to console.log but that is not generally visible to the user.

### Flavor

Docker

### Version

main#43579df

### Relevant log output

```shell
[Error] ERROR – Error: Uncaught (in promise): BV: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":503,"statusText":"OK","url":"https://api.platform.fastenhealth.com/v1/app/ccda-to-fhir","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://api.platform.fastenhealth.com/v1/app/ccda-to-fhir: 503 OK","error":{"message":"Service Unavailable"}}
Error: Uncaught (in promise): BV: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":503,"statusText":"OK","url":"https://api.platform.fastenhealth.com/v1/app/ccda-to-fhir","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://api.platform.fastenhealth.com/v1/app/ccda-to-fhir: 503 OK","error":{"message":"Service Unavailable"}}O — zone.min.js:29:2003(anonymous function) — zone.min.js:29:1070(anonymous function) — zone.min.js:29:1180De — asyncToGenerator.js:6pr — asyncToGenerator.js:29onInvoke — core.mjs:26274(anonymous function) — zone.min.js:14:2296(anonymous function) — zone.min.js:29:2802onInvokeTask — core.mjs:26261(anonymous function) — zone.min.js:14:2963m — zone.min.js:14:10279(anonymous function) — zone.min.js:14:9052y — zone.min.js:45:710_ — zone.min.js:45:1070
	handleError (main.3c3e301da071dd4a.js:1:53482)
	next (main.3c3e301da071dd4a.js:1:120624)
	__tryOrUnsub (main.3c3e301da071dd4a.js:1:4963)
	next (main.3c3e301da071dd4a.js:1:4216)
	_next (main.3c3e301da071dd4a.js:1:3407)
	next (main.3c3e301da071dd4a.js:1:3182)
	next (main.3c3e301da071dd4a.js:1:7849)
	emit (main.3c3e301da071dd4a.js:1:100935)
	(anonymous function) (zone.min.js:14:2296)
	onHandleError (main.3c3e301da071dd4a.js:1:114819)
	(anonymous function) (zone.min.js:14:2514)
	e (zone.min.js:29:594)
	(anonymous function) (zone.min.js:29:781)
	m (zone.min.js:14:10346)
	(anonymous function) (zone.min.js:14:9052)
	y (zone.min.js:45:710)
	_ (zone.min.js:45:1070)
```

**Comment by alustig** [comment]
I encountered the same bug while uploading an XML file with CCDA format. The api appears to be `503 (Service Unavailable)`
I'm using the latest `ghcr.io/fastenhealth/fasten-onprem:main` Docker image

```  
POST https://api.platform.fastenhealth.com/v1/app/ccda-to-fhir 503 (Service Unavailable)
ERROR Error: Uncaught (in promise): BV: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":503,"statusText":"OK","url":"https://api.platform.fastenhealth.com/v1/app/ccda-to-fhir","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://api.platform.fastenhealth.com/v1/app/ccda-to-fhir: 503 OK","error":{"message":"Service Unavailable"}}
    at O (zone.min.js:29:1993)
    at zone.min.js:29:1068
    at zone.min.js:29:1174
    at De (asyncToGenerator.js:6:1)
    at pr (asyncToGenerator.js:29:1)
    at e.invoke (zone.min.js:14:7205)
    at Object.onInvoke (core.mjs:26274:33)
    at e.invoke (zone.min.js:14:7145)
    at t.run (zone.min.js:14:2289)
    at zone.min.js:29:2798
```
