### ISSUE TITLE
[Bug][Epic]: Error While Importing from Fastmed

### ISSUE THREAD

**Issue by tetra-archos** [fastenhealth/fasten-onprem#460]
### Contact Details

matt.church.whitlow@gmail.com

### What happened?

Using the Epic Import for FastMed got the attached error

Not sure why I have no errors from other imports.

### Flavor

Docker

### Version

main#d0f2080

### Relevant log output

```shell
An error occurred while initializing external data source connection: '{"stack":"TypeError: Failed to fetch\n at http://192.168.1.114:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:5826\n at a.<computed> (http://192.168.1.114:9090/web/assets/js/lforms/assets/lib/zone.min.js:22:3126)\n at http://192.168.1.114:9090/web/main.1c7d3169183c209a.js:1:757695\n at Generator.next (<anonymous>)\n at De (http://192.168.1.114:9090/web/polyfills.5ca82281f9682ff9.js:1:215358)\n at kt (http://192.168.1.114:9090/web/polyfills.5ca82281f9682ff9.js:1:215584)\n at e.invoke (http://192.168.1.114:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:7205)\n at Object.onInvoke (http://192.168.1.114:9090/web/main.1c7d3169183c209a.js:1:114508)\n at e.invoke (http://192.168.1.114:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:7145)\n at t.run (http://192.168.1.114:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:2289)","message":"Failed to fetch"}'
```

**Comment by AnalogJ** [comment]
Can you retry?

**Comment by tetra-archos** [comment]
same issue persists

**Comment by AnalogJ** [comment]
We're making changes to the way that Epic providers work in Jan. Should hopefully fix this issue.
